let consignmentState={locations:[],consignments:[],items:[],clients:[],orders:[],products:[],summary:{}};
const consMoney=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const consDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
async function consList(r,limit=1000){const x=await RelationalAPI.list(r,limit,0);return x.items||[];}
async function loadConsignments(){
 try{
  const [locations,consignments,items,clients,orders,products,summary]=await Promise.all([
   consList('consignment_locations'),consList('consignments'),consList('consignment_items'),consList('clients'),consList('orders'),consList('products'),fetch('/api/relational/consignments-summary',{cache:'no-store'}).then(r=>r.json())
  ]);
  consignmentState={locations,consignments,items,clients,orders,products,summary};
  document.getElementById('consActive').textContent=summary.active||0;
  document.getElementById('consOverdue').textContent=summary.overdue||0;
  document.getElementById('consStockValue').textContent=consMoney(summary.stock_value);
  document.getElementById('consOwnerAmount').textContent=consMoney(summary.owner_amount);
  renderConsignments(); updateConsignmentDashboard(summary);
 }catch(e){console.error(e); if(typeof showToast==='function')showToast('Erro ao carregar consignações: '+e.message,'error');}
}
function renderConsignments(){
 const box=document.getElementById('consignmentsList'); if(!box)return;
 const q=(document.getElementById('consSearch')?.value||'').toLowerCase(); const st=document.getElementById('consStatusFilter')?.value||'';
 const rows=consignmentState.consignments.filter(c=>!st||c.status===st).filter(c=>{const loc=consignmentState.locations.find(x=>x.id===c.location_id);const cli=consignmentState.clients.find(x=>x.id===c.client_id);return !q||`${c.id} ${loc?.name||''} ${cli?.name||''} ${c.order_id||''}`.toLowerCase().includes(q)});
 if(!rows.length){box.innerHTML='<div class="col-12"><div class="text-center text-body-secondary py-5"><i class="bi bi-box-seam fs-1 d-block mb-2"></i><h3 class="h6">Nenhuma consignação encontrada</h3><p class="small mb-3">Ajuste os filtros ou crie uma nova consignação.</p><button class="btn btn-primary btn-sm" onclick="openConsignmentModal()">Nova consignação</button></div></div>';return;}
 box.innerHTML=rows.map(c=>{
  const loc=consignmentState.locations.find(x=>x.id===c.location_id),cli=consignmentState.clients.find(x=>x.id===c.client_id),items=consignmentState.items.filter(x=>x.consignment_id===c.id);
  const sent=items.reduce((a,x)=>a+Number(x.quantity_sent||0),0),sold=items.reduce((a,x)=>a+Number(x.quantity_sold||0),0),returned=items.reduce((a,x)=>a+Number(x.quantity_returned||0),0),available=sent-sold-returned;
  const overdue=c.status==='active'&&c.due_date<new Date().toISOString().slice(0,10),pct=sent?Math.min(100,Math.round(((sold+returned)/sent)*100)):0;
  const state=c.status==='active'?['Ativa','success']:c.status==='closed'?['Finalizada','secondary']:['Cancelada','danger'];
  return `<div class="col-12 col-xl-6"><article class="card s3d-consignment-card h-100 ${overdue?'border-danger':''}"><div class="card-body d-flex flex-column">
    <div class="d-flex justify-content-between align-items-start gap-3 mb-3"><div class="min-w-0"><div class="d-flex flex-wrap gap-1 mb-2"><span class="badge text-bg-${state[1]}">${state[0]}</span>${overdue?'<span class="badge text-bg-danger">Vencida</span>':''}${c.order_id?`<span class="badge text-bg-light border">Pedido #${c.order_id}</span>`:''}</div><h3 class="h5 mb-1 text-truncate">${h(loc?.name||'Local não informado')}</h3><p class="small text-body-secondary mb-0 text-truncate"><i class="bi bi-person me-1"></i>${h(cli?.name||'Cliente não vinculado')}</p></div><div class="text-end flex-shrink-0"><small class="text-body-secondary d-block">Comissão</small><strong class="fs-4">${Number(c.commission_pct||0).toFixed(1)}%</strong></div></div>
    <div class="row g-2 mb-3"><div class="col-4"><div class="s3d-cons-metric"><small>Enviadas</small><strong>${sent}</strong></div></div><div class="col-4"><div class="s3d-cons-metric"><small>Vendidas</small><strong class="text-success">${sold}</strong></div></div><div class="col-4"><div class="s3d-cons-metric"><small>No local</small><strong>${available}</strong></div></div></div>
    <div class="mb-3"><div class="d-flex justify-content-between small mb-1"><span class="text-body-secondary">Movimentação</span><strong>${pct}%</strong></div><div class="progress" style="height:.45rem"><div class="progress-bar" style="width:${pct}%"></div></div></div>
    <div class="small text-body-secondary d-flex flex-wrap justify-content-between gap-2 mb-3"><span><i class="bi bi-calendar-event me-1"></i>${consDate(c.start_date)}</span><span class="${overdue?'text-danger fw-semibold':''}"><i class="bi bi-calendar-check me-1"></i>${consDate(c.due_date)}</span></div>
    <div class="d-flex flex-wrap gap-2 mt-auto pt-3 border-top"><button class="btn btn-sm btn-primary flex-grow-1" onclick="openConsignmentDetails(${c.id})"><i class="bi bi-clipboard-check me-1"></i>Gerenciar</button>${c.status==='active'?`<button class="btn btn-sm btn-outline-secondary" onclick="closeConsignment(${c.id})"><i class="bi bi-check2-circle me-1"></i>Finalizar</button>`:''}</div>
  </div></article></div>`;
 }).join('');
}
function openConsignmentLocationModal(){
 if(!consignmentState.clients.filter(x=>!x.deleted_at).length){showToast('Cadastre primeiro um cliente para vinculá-lo ao local','warning');return;}
 document.getElementById('modalTitle').innerHTML='<i class="bi bi-shop"></i> Novo local de consignação';
 document.getElementById('modalBody').innerHTML=`<form id="consLocationForm" onsubmit="saveConsignmentLocation(event)"><div class="alert alert-info py-2"><i class="bi bi-info-circle"></i> Todo local de consignação deve estar vinculado a um cliente cadastrado.</div><div class="row g-3"><div class="col-md-8"><label class="form-label">Nome do local *</label><input id="clName" class="form-control" required></div><div class="col-md-4"><label class="form-label">Comissão do local (%) *</label><input id="clPct" class="form-control" type="number" min="0" max="100" step="0.01" required></div><div class="col-md-6"><label class="form-label">Cliente responsável pelo local *</label><select id="clClient" class="form-select" required><option value="">Selecione o cliente</option>${consignmentState.clients.filter(x=>!x.deleted_at).map(x=>`<option value="${x.id}">${h(x.name)}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Contato no local</label><input id="clContact" class="form-control"></div><div class="col-md-6"><label class="form-label">Telefone</label><input id="clPhone" class="form-control"></div><div class="col-12"><label class="form-label">Endereço do ponto</label><input id="clAddress" class="form-control"></div></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit">Salvar local</button></div></form>`;openModal();
}
async function saveConsignmentLocation(e){e.preventDefault();try{if(!clClient.value)throw new Error('Selecione o cliente responsável pelo local');await RelationalAPI.create('consignment_locations',{name:clName.value.trim(),commission_pct:Number(clPct.value),client_id:Number(clClient.value),contact:clContact.value.trim(),phone:clPhone.value.trim(),address:clAddress.value.trim(),active:true,created_at:new Date().toISOString()});closeModal();await loadConsignments();showToast('Local cadastrado e vinculado ao cliente','success');}catch(x){showToast(x.message,'error');}}
function openConsignmentModal(){
 const validLocations=consignmentState.locations.filter(x=>x.active!==false&&x.client_id&&consignmentState.clients.some(c=>c.id===x.client_id&&!c.deleted_at));
 const validProducts=consignmentState.products.filter(x=>x.active!==false&&!x.deleted_at);
 if(!validLocations.length){showToast('Cadastre um cliente e habilite a aba Consignação no cadastro dele','warning'); if(typeof switchTab==='function') switchTab('clients'); return;}
 if(!validProducts.length){showToast('Cadastre primeiro um produto para consignar','warning');return;}
 const today=new Date().toISOString().slice(0,10), due=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
 document.getElementById('modalTitle').innerHTML='<i class="bi bi-box-arrow-right"></i> Nova consignação';
 document.getElementById('modalBody').innerHTML=`<form id="consForm" onsubmit="saveConsignment(event)"><div class="alert alert-primary py-2"><i class="bi bi-diagram-3"></i> Escolha o cliente consignatário. Os dados do local, comissão e prazo são carregados automaticamente do cadastro do cliente.</div><div class="row g-3"><div class="col-md-6"><label class="form-label">Cliente / local consignatário *</label><select id="cLocation" class="form-select" required><option value="">Selecione</option>${validLocations.map(x=>{const cli=consignmentState.clients.find(c=>c.id===x.client_id);return `<option value="${x.id}">${h(x.name)} · ${h(cli?.name||'Cliente')}</option>`}).join('')}</select></div><div class="col-md-3"><label class="form-label">Cliente vinculado</label><input id="cClientName" class="form-control" readonly placeholder="Selecione o local"></div><div class="col-md-3"><label class="form-label">Comissão (%)</label><input id="cPct" class="form-control" type="number" readonly></div><div class="col-md-6"><label class="form-label">Produto cadastrado *</label><select id="cProduct" class="form-select" required><option value="">Selecione o produto</option>${validProducts.map(x=>`<option value="${x.id}">${h(x.name)} · estoque ${Number(x.stock_qty||0)} · ${consMoney(x.sale_price||0)}</option>`).join('')}</select><div id="cStockHelp" class="form-text">O produto é obrigatório e será reservado do estoque disponível.</div></div><div class="col-md-6"><label class="form-label">Pedido de origem <span class="text-muted">(opcional)</span></label><select id="cOrder" class="form-select" disabled><option value="">Nenhum pedido</option></select><div class="form-text">São exibidos somente pedidos compatíveis com o cliente e o produto.</div></div><div class="col-md-3"><label class="form-label">Quantidade *</label><input id="cQty" type="number" min="1" class="form-control" value="1" required></div><div class="col-md-3"><label class="form-label">Preço unitário *</label><input id="cPrice" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-3"><label class="form-label">Seu valor/unidade</label><input id="cOwnerPreview" class="form-control" readonly></div><div class="col-md-3"><label class="form-label">Saldo após envio</label><input id="cStockAfter" class="form-control" readonly></div><div class="col-md-3"><label class="form-label">Data de saída *</label><input id="cStart" type="date" class="form-control" value="${today}" required></div><div class="col-md-3"><label class="form-label">Retorno/acerto *</label><input id="cDue" type="date" class="form-control" value="${due}" required></div><div class="col-12"><label class="form-label">Observações</label><textarea id="cNotes" class="form-control" rows="2"></textarea></div></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit"><i class="bi bi-box-arrow-right"></i> Criar consignação</button></div></form>`;
 document.getElementById('cLocation').addEventListener('change',applyConsignmentLocation);
 document.getElementById('cProduct').addEventListener('change',applyConsignmentProduct);
 ['cPrice','cQty'].forEach(id=>document.getElementById(id).addEventListener('input',updateConsPreview));
 openModal();
}
function refreshCompatibleOrders(){
 const location=consignmentState.locations.find(x=>x.id===Number(cLocation.value));
 const productId=Number(cProduct.value||0); const select=document.getElementById('cOrder'); if(!select)return;
 const rows=consignmentState.orders.filter(x=>!x.deleted_at&&(!location?.client_id||Number(x.client_id)===Number(location.client_id))&&(!productId||!x.product_id||Number(x.product_id)===productId));
 select.innerHTML='<option value="">Nenhum pedido</option>'+rows.map(x=>`<option value="${x.id}">#${x.id} · ${consMoney(x.total_price)} · ${h(x.status||'')}</option>`).join('');
 select.disabled=!(location&&productId);
}
function applyConsignmentLocation(){
 const loc=consignmentState.locations.find(x=>x.id===Number(cLocation.value)); const cli=consignmentState.clients.find(x=>x.id===loc?.client_id);
 cClientName.value=cli?.name||''; cPct.value=loc?.commission_pct??0; const days=Math.max(1,Number(loc?.default_days||30)); const startValue=document.getElementById('cStart')?.value||new Date().toISOString().slice(0,10); if(document.getElementById('cDue')) document.getElementById('cDue').value=new Date(new Date(startValue+'T12:00:00').getTime()+days*86400000).toISOString().slice(0,10); refreshCompatibleOrders(); updateConsPreview();
}
function applyConsignmentProduct(){
 const product=consignmentState.products.find(x=>x.id===Number(cProduct.value));
 cPrice.value=product?.sale_price??0; cQty.max=Number(product?.stock_qty||0); cStockHelp.textContent=product?`Estoque disponível: ${Number(product.stock_qty||0)} unidade(s).`:'Selecione um produto cadastrado.';
 refreshCompatibleOrders(); updateConsPreview();
}
function updateConsPreview(){
 const p=Number(document.getElementById('cPrice')?.value||0),pct=Number(document.getElementById('cPct')?.value||0),qty=Number(document.getElementById('cQty')?.value||0); const product=consignmentState.products.find(x=>x.id===Number(document.getElementById('cProduct')?.value));
 const owner=document.getElementById('cOwnerPreview'); if(owner)owner.value=consMoney(p*(1-pct/100)); const after=document.getElementById('cStockAfter'); if(after)after.value=product?String(Number(product.stock_qty||0)-qty):'';
}
async function saveConsignment(e){
 e.preventDefault();
 try{
  const location=consignmentState.locations.find(x=>x.id===Number(cLocation.value)); const product=consignmentState.products.find(x=>x.id===Number(cProduct.value)); const qty=Number(cQty.value);
  if(!location?.client_id)throw new Error('O local precisa estar vinculado a um cliente'); if(!product)throw new Error('Selecione o produto a consignar'); if(qty>Number(product.stock_qty||0))throw new Error(`Estoque insuficiente. Disponível: ${Number(product.stock_qty||0)}`);
  const r=await fetch('/api/relational/transactions/consignment-create',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({location_id:location.id,product_id:product.id,order_id:cOrder.value?Number(cOrder.value):null,start_date:cStart.value,due_date:cDue.value,commission_pct:Number(cPct.value),quantity_sent:qty,unit_price:Number(cPrice.value),notes:cNotes.value.trim()})});
  const d=await r.json(); if(!r.ok||d.ok===false)throw new Error(d.error||'Erro ao criar consignação'); closeModal(); await loadConsignments(); if(typeof loadProducts==='function')await loadProducts(); showToast('Produto enviado para consignação','success');
 }catch(x){showToast(x.message,'error');}
}
function openConsignmentDetails(id){const c=consignmentState.consignments.find(x=>x.id===id),loc=consignmentState.locations.find(x=>x.id===c.location_id),items=consignmentState.items.filter(x=>x.consignment_id===id);document.getElementById('modalTitle').innerHTML=`<i class="bi bi-shop"></i> ${h(loc?.name||'Consignação')}`;document.getElementById('modalBody').innerHTML=`<div class="alert alert-info">Comissão do local: <strong>${Number(c.commission_pct).toFixed(1)}%</strong> · Período: ${consDate(c.start_date)} a ${consDate(c.due_date)}</div>${items.map(i=>{const av=i.quantity_sent-i.quantity_sold-i.quantity_returned;return `<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><div><strong>${h(i.description)}</strong><small class="d-block">Enviadas ${i.quantity_sent} · Vendidas ${i.quantity_sold} · Devolvidas ${i.quantity_returned}</small></div><strong>${consMoney(i.unit_price)}</strong></div><div class="mt-3 d-flex gap-2 flex-wrap">${av>0&&c.status==='active'?`<button class="btn btn-sm btn-success" onclick="openSettlementModal(${i.id})">Registrar venda</button><button class="btn btn-sm btn-outline-secondary" onclick="returnConsignmentItem(${i.id})">Registrar devolução</button>`:''}<span class="badge text-bg-light align-self-center">Saldo: ${av}</span></div></div>`}).join('')||'<p>Sem itens.</p>'}`;openModal();}
function openSettlementModal(itemId){const i=consignmentState.items.find(x=>x.id===itemId),c=consignmentState.consignments.find(x=>x.id===i.consignment_id),av=i.quantity_sent-i.quantity_sold-i.quantity_returned;document.getElementById('modalTitle').textContent='Registrar venda consignada';document.getElementById('modalBody').innerHTML=`<form onsubmit="saveSettlement(event,${itemId})"><p><strong>${h(i.description)}</strong> · saldo ${av}</p><div class="row g-3"><div class="col-md-4"><label class="form-label">Quantidade vendida</label><input id="settleQty" class="form-control" type="number" min="1" max="${av}" value="1" required></div><div class="col-md-4"><label class="form-label">Data do acerto</label><input id="settleDate" class="form-control" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="col-12"><div class="alert alert-success">Bruto/unidade: ${consMoney(i.unit_price)} · Local: ${c.commission_pct}% · Seu valor/unidade: <strong>${consMoney(i.unit_price*(1-c.commission_pct/100))}</strong></div></div><div class="col-12"><label class="form-label">Observações</label><textarea id="settleNotes" class="form-control"></textarea></div></div><div class="text-end mt-3"><button class="btn btn-success">Confirmar venda</button></div></form>`;openModal();}
async function saveSettlement(e,itemId){e.preventDefault();try{const r=await fetch('/api/relational/transactions/consignment-settlement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:itemId,quantity_sold:Number(settleQty.value),settlement_date:settleDate.value,notes:settleNotes.value})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Erro no acerto');closeModal();await loadConsignments();if(typeof loadFinanceDashboard==='function')await loadFinanceDashboard();showToast('Venda consignada registrada e integrada ao Financeiro','success');}catch(x){showToast(x.message,'error');}}
function returnConsignmentItem(itemId){const i=consignmentState.items.find(x=>x.id===itemId),av=i.quantity_sent-i.quantity_sold-i.quantity_returned;document.getElementById('modalTitle').textContent='Registrar devolução';document.getElementById('modalBody').innerHTML=`<form onsubmit="saveConsignmentReturn(event,${itemId})"><p><strong>${h(i.description)}</strong> · saldo ${av}</p><label class="form-label">Quantidade devolvida</label><input id="returnQty" class="form-control" type="number" min="1" max="${av}" value="1" required><div class="text-end mt-3"><button class="btn btn-primary">Confirmar devolução</button></div></form>`;openModal();}
async function saveConsignmentReturn(e,itemId){e.preventDefault();try{const r=await fetch('/api/relational/transactions/consignment-return',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:itemId,quantity_returned:Number(returnQty.value)})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Erro na devolução');closeModal();await loadConsignments();if(typeof loadProducts==='function')await loadProducts();showToast('Devolução registrada e estoque atualizado','success');}catch(x){showToast(x.message,'error');}}
async function closeConsignment(id){const pending=consignmentState.items.filter(x=>x.consignment_id===id).reduce((a,x)=>a+Number(x.quantity_sent||0)-Number(x.quantity_sold||0)-Number(x.quantity_returned||0),0);if(pending>0){showToast(`Ainda existem ${pending} unidade(s) no local. Registre venda ou devolução antes de finalizar.`,'warning');return;}if(!confirm('Finalizar esta consignação?'))return;try{await RelationalAPI.update('consignments',id,{status:'closed',closed_at:new Date().toISOString()});await loadConsignments();showToast('Consignação finalizada','success');}catch(x){showToast(x.message,'error');}}
function updateConsignmentDashboard(s){const map=[['dashConsActive',s.active||0],['dashConsOverdue',s.overdue||0],['dashConsOwner',consMoney(s.owner_amount||0)]];map.forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=v;});}
