let consignmentState={locations:[],consignments:[],items:[],clients:[],orders:[],products:[],summary:{}};
const consMoney=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const consDate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'—';
async function consList(r,limit=1000){const x=await RelationalAPI.list(r,limit,0);return x.items||[];}
async function loadConsignments(){
 try{
  const [locations,consignments,items,clients,orders,products,summary]=await Promise.all([
   consList('consignment_locations'),consList('consignments'),consList('consignment_items'),consList('clients'),consList('orders'),consList('products'),fetch('/api/relational/consignments-summary',{cache:'no-store'}).then(r=>r.json())
  ]);
  consignmentState={locations,consignments,items,clients,orders,products,summary};
  document.getElementById('consActive').textContent=summary.active||0;
  document.getElementById('consOverdue').textContent=summary.overdue||0;
  document.getElementById('consStockValue').textContent=consMoney(summary.stock_value);
  document.getElementById('consOwnerAmount').textContent=consMoney(summary.owner_amount);
  renderConsignments(); updateConsignmentDashboard(summary);
 }catch(e){console.error(e); if(typeof showToast==='function')showToast('Erro ao carregar consignações: '+e.message,'error');}
}
function renderConsignments(){
 const box=document.getElementById('consignmentsList'); if(!box)return;
 const q=(document.getElementById('consSearch')?.value||'').toLowerCase(); const st=document.getElementById('consStatusFilter')?.value||'';
 const rows=consignmentState.consignments.filter(c=>!st||c.status===st).filter(c=>{
  const loc=consignmentState.locations.find(x=>x.id===c.location_id); const cli=consignmentState.clients.find(x=>x.id===c.client_id);
  const text=`${c.id} ${loc?.name||''} ${cli?.name||''} ${c.order_id||''}`.toLowerCase(); return !q||text.includes(q);
 });
 if(!rows.length){box.innerHTML='<div class="col-12"><div class="empty-state"><i class="bi bi-box-seam"></i><h3>Nenhuma consignação encontrada</h3><p>Crie uma consignação para acompanhar peças deixadas em parceiros.</p></div></div>';return;}
 box.innerHTML=rows.map(c=>{
  const loc=consignmentState.locations.find(x=>x.id===c.location_id); const cli=consignmentState.clients.find(x=>x.id===c.client_id);
  const items=consignmentState.items.filter(x=>x.consignment_id===c.id); const sent=items.reduce((a,x)=>a+Number(x.quantity_sent||0),0); const sold=items.reduce((a,x)=>a+Number(x.quantity_sold||0),0); const returned=items.reduce((a,x)=>a+Number(x.quantity_returned||0),0); const available=sent-sold-returned;
  const overdue=c.status==='active'&&c.due_date<new Date().toISOString().slice(0,10); const pct=sent?Math.round(((sold+returned)/sent)*100):0;
  return `<div class="col-12 col-xl-6"><article class="modern-card h-100 consignment-card ${overdue?'border-danger':''}">
   <div class="d-flex justify-content-between gap-3"><div><span class="badge ${c.status==='active'?'text-bg-success':c.status==='closed'?'text-bg-secondary':'text-bg-danger'}">${c.status==='active'?'Ativa':c.status==='closed'?'Finalizada':'Cancelada'}</span>${overdue?'<span class="badge text-bg-danger ms-1">Vencida</span>':''}<h3 class="h5 mt-2 mb-1">${h(loc?.name||'Local não informado')}</h3><small>${h(cli?.name||'Sem cliente vinculado')} ${c.order_id?'· Pedido #'+c.order_id:''}</small></div><div class="text-end"><small>Comissão</small><strong class="d-block fs-4">${Number(c.commission_pct||0).toFixed(1)}%</strong></div></div>
   <div class="row g-2 my-3"><div class="col-4"><div class="p-2 rounded bg-body-tertiary"><small>Enviadas</small><strong class="d-block">${sent}</strong></div></div><div class="col-4"><div class="p-2 rounded bg-body-tertiary"><small>Vendidas</small><strong class="d-block text-success">${sold}</strong></div></div><div class="col-4"><div class="p-2 rounded bg-body-tertiary"><small>No local</small><strong class="d-block">${available}</strong></div></div></div>
   <div class="progress mb-2" style="height:8px"><div class="progress-bar" style="width:${pct}%"></div></div><div class="d-flex justify-content-between"><small>${consDate(c.start_date)} até ${consDate(c.due_date)}</small><small>${pct}% movimentado</small></div>
   <div class="mt-3 d-flex gap-2 flex-wrap"><button class="btn btn-sm btn-primary" onclick="openConsignmentDetails(${c.id})"><i class="bi bi-eye"></i> Detalhes e acerto</button>${c.status==='active'?`<button class="btn btn-sm btn-outline-secondary" onclick="closeConsignment(${c.id})"><i class="bi bi-check2-circle"></i> Finalizar</button>`:''}</div>
  </article></div>`;
 }).join('');
}
function openConsignmentLocationModal(){
 document.getElementById('modalTitle').innerHTML='<i class="bi bi-shop"></i> Novo local de consignação';
 document.getElementById('modalBody').innerHTML=`<form id="consLocationForm" onsubmit="saveConsignmentLocation(event)"><div class="row g-3"><div class="col-md-8"><label class="form-label">Nome do local *</label><input id="clName" class="form-control" required></div><div class="col-md-4"><label class="form-label">Comissão do local (%) *</label><input id="clPct" class="form-control" type="number" min="0" max="100" step="0.01" required></div><div class="col-md-6"><label class="form-label">Cliente vinculado</label><select id="clClient" class="form-select"><option value="">Nenhum</option>${consignmentState.clients.map(x=>`<option value="${x.id}">${h(x.name)}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Contato</label><input id="clContact" class="form-control"></div><div class="col-md-6"><label class="form-label">Telefone</label><input id="clPhone" class="form-control"></div><div class="col-12"><label class="form-label">Endereço</label><input id="clAddress" class="form-control"></div></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit">Salvar local</button></div></form>`;openModal();
}
async function saveConsignmentLocation(e){e.preventDefault();try{await RelationalAPI.create('consignment_locations',{name:clName.value.trim(),commission_pct:Number(clPct.value),client_id:clClient.value?Number(clClient.value):null,contact:clContact.value.trim(),phone:clPhone.value.trim(),address:clAddress.value.trim(),active:true,created_at:new Date().toISOString()});closeModal();await loadConsignments();showToast('Local cadastrado','success');}catch(x){showToast(x.message,'error');}}
function openConsignmentModal(){
 if(!consignmentState.locations.length){showToast('Cadastre primeiro um local de consignação','warning');openConsignmentLocationModal();return;}
 const today=new Date().toISOString().slice(0,10), due=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
 document.getElementById('modalTitle').innerHTML='<i class="bi bi-box-arrow-right"></i> Nova consignação';
 document.getElementById('modalBody').innerHTML=`<form id="consForm" onsubmit="saveConsignment(event)"><div class="row g-3"><div class="col-md-6"><label class="form-label">Local *</label><select id="cLocation" class="form-select" required onchange="applyLocationPct()"><option value="">Selecione</option>${consignmentState.locations.filter(x=>x.active!==false).map(x=>`<option value="${x.id}" data-pct="${x.commission_pct}">${h(x.name)}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label">Comissão (%) *</label><input id="cPct" class="form-control" type="number" min="0" max="100" step="0.01" required></div><div class="col-md-3"><label class="form-label">Pedido vinculado</label><select id="cOrder" class="form-select"><option value="">Nenhum</option>${consignmentState.orders.filter(x=>!x.deleted_at).map(x=>`<option value="${x.id}" data-client="${x.client_id||''}" data-product="${x.product_id||''}" data-price="${x.unit_price||0}">#${x.id} · ${consMoney(x.total_price)}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Cliente</label><select id="cClient" class="form-select"><option value="">Nenhum</option>${consignmentState.clients.filter(x=>!x.deleted_at).map(x=>`<option value="${x.id}">${h(x.name)}</option>`).join('')}</select></div><div class="col-md-3"><label class="form-label">Saída *</label><input id="cStart" type="date" class="form-control" value="${today}" required></div><div class="col-md-3"><label class="form-label">Retorno/acerto *</label><input id="cDue" type="date" class="form-control" value="${due}" required></div><hr><div class="col-md-6"><label class="form-label">Produto</label><select id="cProduct" class="form-select" onchange="applyProductData()"><option value="">Peça avulsa</option>${consignmentState.products.filter(x=>x.active!==false&&!x.deleted_at).map(x=>`<option value="${x.id}" data-name="${h(x.name)}" data-price="${x.sale_price||0}">${h(x.name)}</option>`).join('')}</select></div><div class="col-md-6"><label class="form-label">Descrição da peça *</label><input id="cDescription" class="form-control" required></div><div class="col-md-4"><label class="form-label">Quantidade *</label><input id="cQty" type="number" min="1" class="form-control" value="1" required></div><div class="col-md-4"><label class="form-label">Preço unitário *</label><input id="cPrice" type="number" min="0" step="0.01" class="form-control" required></div><div class="col-md-4"><label class="form-label">Seu valor/unidade</label><input id="cOwnerPreview" class="form-control" readonly></div><div class="col-12"><label class="form-label">Observações</label><textarea id="cNotes" class="form-control" rows="2"></textarea></div></div><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit">Criar consignação</button></div></form>`;
 ['cPct','cPrice'].forEach(id=>document.getElementById(id).addEventListener('input',updateConsPreview)); document.getElementById('cOrder').addEventListener('change',applyOrderData);openModal();
}
function applyLocationPct(){const o=cLocation.selectedOptions[0];cPct.value=o?.dataset.pct||0;const loc=consignmentState.locations.find(x=>x.id===Number(cLocation.value));if(loc?.client_id)cClient.value=loc.client_id;updateConsPreview();}
function applyProductData(){const o=cProduct.selectedOptions[0];if(o?.dataset.name)cDescription.value=o.dataset.name;if(o?.dataset.price)cPrice.value=o.dataset.price;updateConsPreview();}
function applyOrderData(){const o=cOrder.selectedOptions[0];if(o?.dataset.client)cClient.value=o.dataset.client;if(o?.dataset.product){cProduct.value=o.dataset.product;applyProductData();}if(o?.dataset.price)cPrice.value=o.dataset.price;}
function updateConsPreview(){const p=Number(cPrice?.value||0),pct=Number(cPct?.value||0);if(window.cOwnerPreview)cOwnerPreview.value=consMoney(p*(1-pct/100));}
async function saveConsignment(e){e.preventDefault();try{const created=await RelationalAPI.create('consignments',{location_id:Number(cLocation.value),client_id:cClient.value?Number(cClient.value):null,order_id:cOrder.value?Number(cOrder.value):null,start_date:cStart.value,due_date:cDue.value,commission_pct:Number(cPct.value),status:'active',notes:cNotes.value.trim(),created_at:new Date().toISOString()});const cons=created.item||created.data||created;await RelationalAPI.create('consignment_items',{consignment_id:cons.id,product_id:cProduct.value?Number(cProduct.value):null,description:cDescription.value.trim(),quantity_sent:Number(cQty.value),quantity_sold:0,quantity_returned:0,unit_price:Number(cPrice.value),created_at:new Date().toISOString()});closeModal();await loadConsignments();showToast('Consignação criada','success');}catch(x){showToast(x.message,'error');}}
function openConsignmentDetails(id){const c=consignmentState.consignments.find(x=>x.id===id),loc=consignmentState.locations.find(x=>x.id===c.location_id),items=consignmentState.items.filter(x=>x.consignment_id===id);document.getElementById('modalTitle').innerHTML=`<i class="bi bi-shop"></i> ${h(loc?.name||'Consignação')}`;document.getElementById('modalBody').innerHTML=`<div class="alert alert-info">Comissão do local: <strong>${Number(c.commission_pct).toFixed(1)}%</strong> · Período: ${consDate(c.start_date)} a ${consDate(c.due_date)}</div>${items.map(i=>{const av=i.quantity_sent-i.quantity_sold-i.quantity_returned;return `<div class="border rounded p-3 mb-3"><div class="d-flex justify-content-between"><div><strong>${h(i.description)}</strong><small class="d-block">Enviadas ${i.quantity_sent} · Vendidas ${i.quantity_sold} · Devolvidas ${i.quantity_returned}</small></div><strong>${consMoney(i.unit_price)}</strong></div><div class="mt-3 d-flex gap-2 flex-wrap">${av>0&&c.status==='active'?`<button class="btn btn-sm btn-success" onclick="openSettlementModal(${i.id})">Registrar venda</button><button class="btn btn-sm btn-outline-secondary" onclick="returnConsignmentItem(${i.id})">Registrar devolução</button>`:''}<span class="badge text-bg-light align-self-center">Saldo: ${av}</span></div></div>`}).join('')||'<p>Sem itens.</p>'}`;openModal();}
function openSettlementModal(itemId){const i=consignmentState.items.find(x=>x.id===itemId),c=consignmentState.consignments.find(x=>x.id===i.consignment_id),av=i.quantity_sent-i.quantity_sold-i.quantity_returned;document.getElementById('modalTitle').textContent='Registrar venda consignada';document.getElementById('modalBody').innerHTML=`<form onsubmit="saveSettlement(event,${itemId})"><p><strong>${h(i.description)}</strong> · saldo ${av}</p><div class="row g-3"><div class="col-md-4"><label class="form-label">Quantidade vendida</label><input id="settleQty" class="form-control" type="number" min="1" max="${av}" value="1" required></div><div class="col-md-4"><label class="form-label">Data do acerto</label><input id="settleDate" class="form-control" type="date" value="${new Date().toISOString().slice(0,10)}" required></div><div class="col-12"><div class="alert alert-success">Bruto/unidade: ${consMoney(i.unit_price)} · Local: ${c.commission_pct}% · Seu valor/unidade: <strong>${consMoney(i.unit_price*(1-c.commission_pct/100))}</strong></div></div><div class="col-12"><label class="form-label">Observações</label><textarea id="settleNotes" class="form-control"></textarea></div></div><div class="text-end mt-3"><button class="btn btn-success">Confirmar venda</button></div></form>`;openModal();}
async function saveSettlement(e,itemId){e.preventDefault();try{const r=await fetch('/api/relational/transactions/consignment-settlement',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({item_id:itemId,quantity_sold:Number(settleQty.value),settlement_date:settleDate.value,notes:settleNotes.value})});const d=await r.json();if(!r.ok||d.ok===false)throw new Error(d.error||'Erro no acerto');closeModal();await loadConsignments();showToast('Venda consignada registrada','success');}catch(x){showToast(x.message,'error');}}
function returnConsignmentItem(itemId){const i=consignmentState.items.find(x=>x.id===itemId),av=i.quantity_sent-i.quantity_sold-i.quantity_returned;document.getElementById('modalTitle').textContent='Registrar devolução';document.getElementById('modalBody').innerHTML=`<form onsubmit="saveConsignmentReturn(event,${itemId})"><p><strong>${h(i.description)}</strong> · saldo ${av}</p><label class="form-label">Quantidade devolvida</label><input id="returnQty" class="form-control" type="number" min="1" max="${av}" value="1" required><div class="text-end mt-3"><button class="btn btn-primary">Confirmar devolução</button></div></form>`;openModal();}
async function saveConsignmentReturn(e,itemId){e.preventDefault();const i=consignmentState.items.find(x=>x.id===itemId);try{await RelationalAPI.update('consignment_items',itemId,{quantity_returned:Number(i.quantity_returned||0)+Number(returnQty.value)});closeModal();await loadConsignments();showToast('Devolução registrada','success');}catch(x){showToast(x.message,'error');}}
async function closeConsignment(id){if(!confirm('Finalizar esta consignação? Registre antes todas as vendas e devoluções.'))return;try{await RelationalAPI.update('consignments',id,{status:'closed',closed_at:new Date().toISOString()});await loadConsignments();showToast('Consignação finalizada','success');}catch(x){showToast(x.message,'error');}}
function updateConsignmentDashboard(s){const map=[['dashConsActive',s.active||0],['dashConsOverdue',s.overdue||0],['dashConsOwner',consMoney(s.owner_amount||0)]];map.forEach(([id,v])=>{const el=document.getElementById(id);if(el)el.textContent=v;});}
