(function(){
'use strict';
const STATUS_FLOW=['quote','approved','paid','printing','post','packaging','shipped','delivered'];
const STATUS_LABEL={quote:'Criado',approved:'Aprovado',paid:'Pago',printing:'Imprimindo',post:'Pós-processamento',packaging:'Embalagem',shipped:'Enviado',delivered:'Entregue',cancelled:'Cancelado'};
let notices=[];
function q(sql,p=[]){try{return db?.exec(sql,p)?.[0]?.values||[]}catch(e){console.warn(e);return[]}}
function buildNotices(){
 if(!window.db)return [];
 const list=[]; const now=Date.now();
 q(`SELECT id,name,stock,min_alert FROM materials WHERE COALESCE(stock,0)<=COALESCE(min_alert,0) ORDER BY stock`).forEach(([id,n,s,m])=>list.push({type:'warning',icon:'🧵',title:'Material em baixa',text:`${n}: ${Number(s||0).toFixed(0)}g disponíveis`,tab:'inventory'}));
 q(`SELECT id,date,status,total_price,COALESCE(paid_amount,0) FROM orders WHERE deleted_at IS NULL AND status NOT IN ('delivered','cancelled','quote')`).forEach(([id,d,status,total,paid])=>{const age=(now-new Date(d).getTime())/86400000;if(age>7)list.push({type:'danger',icon:'⏰',title:'Pedido aguardando há mais de 7 dias',text:`Pedido #${id} · ${Math.floor(age)} dias`,tab:'orders'});if(Number(paid)<Number(total)&&status!=='approved')list.push({type:'info',icon:'💳',title:'Pagamento pendente',text:`Pedido #${id} · saldo R$ ${(Number(total)-Number(paid)).toFixed(2)}`,tab:'finance'});});
 q(`SELECT id,name,lifespan_hours FROM maintenance_items WHERE active=1`).forEach(([id,t,hours])=>{if(Number(hours)<=25)list.push({type:'warning',icon:'🔧',title:'Item de manutenção crítico',text:`${t} · vida útil configurada em ${Number(hours)}h`,tab:'maintenance'});});
 q(`SELECT id,name,COALESCE(hours_used,0),lifetime_hours FROM printers WHERE COALESCE(hours_used,0)>=COALESCE(lifetime_hours,1)*0.8`).forEach(([id,n,used,life])=>list.push({type:'warning',icon:'🛠️',title:'Impressora perto da vida útil',text:`${n}: ${Math.round(Number(used)/Number(life)*100)}% utilizada`,tab:'printers'}));
 q(`SELECT COUNT(*) FROM orders WHERE deleted_at IS NULL AND status='printing'`).forEach(([c])=>{if(c>0)list.unshift({type:'success',icon:'🖨️',title:'Produção em andamento',text:`${c} pedido${c==1?'':'s'} imprimindo agora`,tab:'printers'});});
 return list.slice(0,30);
}
function updateBadge(){if(window.Sprint5){window.Sprint5.renderNotifications();return;}notices=buildNotices();const b=document.getElementById('notificationBadge');if(b){b.textContent=notices.length;b.hidden=!notices.length}}
function renderDrawer(){updateBadge();const body=document.getElementById('notificationList');if(!body)return;body.innerHTML=notices.length?notices.map((n,i)=>`<button class="notice-item ${n.type}" onclick="Phase2UI.openNotice(${i})"><span class="notice-icon">${n.icon}</span><span><strong>${h(n.title)}</strong><small>${h(n.text)}</small></span><span class="notice-arrow">›</span></button>`).join(''):`<div class="notice-empty"><span>✅</span><strong>Tudo em ordem</strong><small>Nenhuma pendência importante agora.</small></div>`}
function toggleDrawer(force){const d=document.getElementById('notificationDrawer');if(!d)return;const open=force??!d.classList.contains('open');d.classList.toggle('open',open);document.body.classList.toggle('notice-open',open);if(open)renderDrawer()}
function openNotice(i){const n=notices[i];toggleDrawer(false);if(n?.tab&&typeof switchTab==='function')switchTab(n.tab,{currentTarget:document.querySelector(`.nav-item[onclick*="'${n.tab}'"]`)});}
function injectTopbar(){const r=document.querySelector('.topbar-right');if(!r||document.getElementById('notificationButton'))return;const wrap=document.createElement('div');wrap.className='notification-wrap';wrap.innerHTML=`<button id="notificationButton" class="ui-icon-btn notification-btn" aria-label="Notificações" title="Notificações">🔔<span id="notificationBadge" class="notification-badge" hidden>0</span></button>`;r.prepend(wrap);wrap.querySelector('button').onclick=()=>toggleDrawer();document.body.insertAdjacentHTML('beforeend',`<div id="noticeBackdrop" class="notice-backdrop" onclick="Phase2UI.toggleDrawer(false)"></div><aside id="notificationDrawer" class="notification-drawer"><header><div><span class="eyebrow">Central</span><h3>Notificações</h3></div><button class="ui-icon-btn" onclick="Phase2UI.toggleDrawer(false)">✕</button></header><div id="notificationList" class="notification-list"></div><footer><button class="btn-ghost" onclick="Phase2UI.refresh()">Atualizar</button></footer></aside>`);}
function orderTimeline(orderId){const r=q(`SELECT o.id,o.status,o.date,o.printing_started_at,COALESCE(c.name,'Sem cliente'),o.total_price,COALESCE(o.paid_amount,0) FROM orders o LEFT JOIN clients c ON c.id=o.client_id WHERE o.id=?`,[orderId]);if(!r.length)return;const [id,status,date,start,client,total,paid]=r[0];const current=STATUS_FLOW.indexOf(status);const cancelled=status==='cancelled';const steps=STATUS_FLOW.map((s,i)=>`<div class="timeline-step ${cancelled?'muted':i<current?'done':i===current?'current':''}"><span>${i<current?'✓':i===current?'●':i+1}</span><div><strong>${STATUS_LABEL[s]}</strong><small>${s==='quote'?new Date(date).toLocaleString('pt-BR'):s==='printing'&&start?new Date(start).toLocaleString('pt-BR'):i<current?'Concluído':'Aguardando'}</small></div></div>`).join('');document.getElementById('modalTitle').innerHTML=`🧭 Linha do tempo — Pedido #${id}`;document.getElementById('modalBody').innerHTML=`<div class="timeline-summary"><div><small>Cliente</small><strong>${h(client)}</strong></div><div><small>Valor</small><strong>R$ ${Number(total).toFixed(2)}</strong></div><div><small>Pagamento</small><strong>R$ ${Number(paid).toFixed(2)}</strong></div></div>${cancelled?'<div class="timeline-cancelled">Pedido cancelado</div>':''}<div class="order-timeline">${steps}</div>`;openModal();}
function printerDashboard(){if(typeof loadPrinters==='function')loadPrinters();const grid=document.getElementById('printerDashboardGrid');if(!grid||!window.db)return;const ps=q(`SELECT id,name,value,lifetime_hours,wattage,speed_gph,COALESCE(hours_used,0) FROM printers ORDER BY name`);const jobs=q(`SELECT o.id,o.printer_id,o.work_type,o.print_time,o.printing_started_at,COALESCE(c.name,'Sem cliente') FROM orders o LEFT JOIN clients c ON c.id=o.client_id WHERE o.deleted_at IS NULL AND o.status='printing'`);grid.innerHTML=ps.length?ps.map(([id,name,value,life,watt,speed,used])=>{const job=jobs.find(j=>Number(j[1])===Number(id));let pct=0,remain='Disponível';if(job){const elapsed=job[4]?(Date.now()-new Date(job[4]).getTime())/3600000:0;pct=Math.min(100,Math.round(elapsed/(Number(job[3])||1)*100));remain=pct>=100?'Previsão concluída':`${Math.max(0,Number(job[3])-elapsed).toFixed(1)}h restantes`;}const lifePct=Math.min(100,Math.round(Number(used)/(Number(life)||1)*100));return `<article class="printer-live-card ${job?'busy':'idle'}"><div class="printer-live-head"><div class="printer-avatar">🖨️</div><div><strong>${h(name)}</strong><small>${job?'Em produção':'Disponível'}</small></div><span class="printer-state">${job?'● Ativa':'● Livre'}</span></div>${job?`<div class="printer-job"><span>Pedido #${job[0]} · ${h(job[5])}</span><strong>${h(getWorkTypeLabel(job[2]))}</strong><div class="printer-progress"><span style="width:${pct}%"></span></div><small>${pct}% · ${remain}</small></div>`:`<div class="printer-empty-job">Pronta para receber um novo trabalho</div>`}<div class="printer-metrics"><div><small>Uso da vida útil</small><strong>${lifePct}%</strong></div><div><small>Potência</small><strong>${Number(watt)}W</strong></div><div><small>Velocidade</small><strong>${Number(speed)}g/h</strong></div></div></article>`}).join(''):`<div class="notice-empty"><span>🖨️</span><strong>Nenhuma impressora cadastrada</strong><small>Cadastre a primeira impressora para acompanhar a operação.</small></div>`;}
function init(){updateBadge();setInterval(updateBadge,30000);document.addEventListener('click',e=>{if(document.body.classList.contains('notice-open')&&!e.target.closest('.notification-drawer')&&!e.target.closest('#notificationButton'))toggleDrawer(false)});}
window.Phase2UI={toggleDrawer,openNotice,refresh:renderDrawer,updateBadge,orderTimeline,printerDashboard};
window.showOrderTimeline=orderTimeline;window.loadPrinterDashboard=printerDashboard;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
