(function(){
'use strict';
const S5={
 q(sql,p=[]){try{return db?.exec(sql,p)?.[0]?.values||[]}catch(e){console.warn('[Sprint5]',e);return[]}},
 esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))},
 syncNotifications(){
  if(!window.db)return;
  const items=[]; const days=Math.max(1,Number(currentSettings?.alertDays||7));
  this.q('SELECT id,name,stock,min_alert FROM materials WHERE COALESCE(stock,0)<=COALESCE(min_alert,0)').forEach(([id,n,s,m])=>items.push({key:`material:${id}`,type:'stock',priority:'high',title:'Material em baixa',message:`${n}: ${Number(s||0).toFixed(0)}g disponíveis (mínimo ${Number(m||0).toFixed(0)}g)`,tab:'inventory'}));
  this.q(`SELECT id,date FROM orders WHERE deleted_at IS NULL AND status NOT IN ('delivered','cancelled') AND julianday('now')-julianday(date)>?`,[days]).forEach(([id])=>items.push({key:`order-delay:${id}`,type:'order',priority:'high',title:`Pedido #${id} atrasado`,message:`Há mais de ${days} dias sem conclusão.`,tab:'orders'}));
  this.q(`SELECT id,total_price,COALESCE(paid_amount,0) FROM orders WHERE deleted_at IS NULL AND status NOT IN ('cancelled','quote') AND COALESCE(paid_amount,0)<COALESCE(total_price,0)`).forEach(([id,t,p])=>items.push({key:`payment:${id}`,type:'finance',priority:'medium',title:`Pagamento pendente #${id}`,message:`Saldo de ${money(Number(t||0)-Number(p||0))}.`,tab:'finance'}));
  const now=new Date().toISOString();
  items.forEach(n=>db.run(`INSERT INTO notifications(notification_key,type,priority,title,message,target_tab,is_read,active,created_at,updated_at) VALUES(?,?,?,?,?,?,0,1,?,?) ON CONFLICT(notification_key) DO UPDATE SET type=excluded.type,priority=excluded.priority,title=excluded.title,message=excluded.message,target_tab=excluded.target_tab,active=1,updated_at=excluded.updated_at`,[n.key,n.type,n.priority,n.title,n.message,n.tab,now,now]));
  const keys=items.map(x=>x.key); if(keys.length){const marks=keys.map(()=>'?').join(',');db.run(`UPDATE notifications SET active=0 WHERE notification_key NOT IN (${marks})`,keys)} else db.run('UPDATE notifications SET active=0');
  persistDB(); this.renderNotifications();
 },
 renderNotifications(){
  const rows=this.q(`SELECT id,priority,title,message,target_tab,is_read,created_at FROM notifications WHERE active=1 ORDER BY is_read, CASE priority WHEN 'high' THEN 1 WHEN 'medium' THEN 2 ELSE 3 END, id DESC`);
  const badge=document.getElementById('notificationBadge'); const unread=rows.filter(r=>!Number(r[5])).length;
  if(badge){badge.textContent=unread;badge.style.display=unread?'':'none'}
  let drawer=document.getElementById('s5NotificationDrawer');
  if(!drawer){drawer=document.createElement('div');drawer.id='s5NotificationDrawer';drawer.className='offcanvas offcanvas-end';drawer.tabIndex=-1;drawer.innerHTML=`<div class="offcanvas-header"><div><h5 class="offcanvas-title">Central de notificações</h5><small class="text-body-secondary">Alertas persistentes da operação</small></div><button class="btn-close" data-bs-dismiss="offcanvas"></button></div><div class="offcanvas-body"><div class="d-flex gap-2 mb-3"><button class="btn btn-sm btn-outline-primary" onclick="Sprint5.markAllRead()">Marcar todas como lidas</button><button class="btn btn-sm btn-outline-secondary" onclick="Sprint5.syncNotifications()">Atualizar</button></div><div id="s5NotificationList"></div></div>`;document.body.appendChild(drawer)}
  const list=document.getElementById('s5NotificationList'); if(!list)return;
  list.innerHTML=rows.length?rows.map(([id,p,t,m,tab,read,dt])=>`<button class="s5-notice ${read?'is-read':''}" onclick="Sprint5.openNotice(${id},'${this.esc(tab)}')"><span class="s5-priority ${p}"></span><span><strong>${this.esc(t)}</strong><small>${this.esc(m)}</small><em>${new Date(dt).toLocaleString('pt-BR')}</em></span></button>`).join(''):`<div class="empty-state"><i class="bi bi-check-circle"></i><strong>Tudo certo</strong><span>Nenhuma pendência ativa.</span></div>`;
 },
 openNotice(id,tab){db.run('UPDATE notifications SET is_read=1 WHERE id=?',[id]);persistDB();this.renderNotifications();bootstrap.Offcanvas.getInstance(document.getElementById('s5NotificationDrawer'))?.hide();if(tab)switchTab(tab)},
 markAllRead(){db.run('UPDATE notifications SET is_read=1 WHERE active=1');persistDB();this.renderNotifications()},
 showNotifications(){this.renderNotifications();bootstrap.Offcanvas.getOrCreateInstance(document.getElementById('s5NotificationDrawer')).show()},
 async openAttachments(entityType,entityId,title='Registro'){
  const rows=this.q('SELECT id,filename,stored_path,mime_type,size_bytes,created_at FROM attachments WHERE entity_type=? AND entity_id=? ORDER BY id DESC',[entityType,String(entityId)]);
  const body=`<div class="attachment-manager"><div class="alert alert-light border"><strong>${this.esc(title)}</strong><div class="small text-body-secondary">Arquivos de até 20 MB: STL, 3MF, imagens, PDF e documentos.</div></div><label class="upload-drop"><i class="bi bi-cloud-arrow-up"></i><strong>Selecionar arquivo</strong><span>O upload começa automaticamente</span><input id="s5AttachmentInput" type="file" hidden></label><div class="attachment-list">${rows.length?rows.map(([id,n,p,m,s,d])=>`<div class="attachment-row"><i class="bi bi-paperclip"></i><div><strong>${this.esc(n)}</strong><small>${(Number(s||0)/1024).toFixed(1)} KB · ${new Date(d).toLocaleString('pt-BR')}</small></div><a class="btn btn-sm btn-outline-primary" href="/api/attachments/download?path=${encodeURIComponent(p)}"><i class="bi bi-download"></i></a><button class="btn btn-sm btn-outline-danger" onclick="Sprint5.deleteAttachment(${id},'${this.esc(p)}','${entityType}','${entityId}','${this.esc(title)}')"><i class="bi bi-trash"></i></button></div>`).join(''):'<div class="empty-state compact"><span>Nenhum anexo neste registro.</span></div>'}</div></div>`;
  showModal(`<i class="bi bi-paperclip"></i> Anexos`,body); setTimeout(()=>document.getElementById('s5AttachmentInput')?.addEventListener('change',e=>this.uploadAttachment(e.target.files[0],entityType,entityId,title)),50)
 },
 async uploadAttachment(file,entityType,entityId,title){if(!file)return;if(file.size>20*1024*1024){showToast('Arquivo maior que 20 MB','error');return}const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)});const resp=await fetch('/api/attachments/upload',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({entity_type:entityType,entity_id:String(entityId),filename:file.name,mime_type:file.type,data})});const out=await resp.json();if(!resp.ok||!out.ok){showToast(out.error||'Falha no upload','error');return}const path=`${entityType}/${String(entityId).replace(/[^A-Za-z0-9_-]/g,'_')}/${out.stored_name}`;db.run('INSERT INTO attachments(entity_type,entity_id,filename,stored_path,mime_type,size_bytes,created_at) VALUES(?,?,?,?,?,?,?)',[entityType,String(entityId),out.filename,path,out.mime_type,out.size_bytes,new Date().toISOString()]);persistDB();showToast('Anexo salvo','success');this.openAttachments(entityType,entityId,title)},
 async deleteAttachment(id,path,entityType,entityId,title){if(!confirm('Remover este anexo?'))return;try{await fetch('/api/attachments/delete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path})});db.run('DELETE FROM attachments WHERE id=?',[id]);persistDB();this.openAttachments(entityType,entityId,title);}catch(e){showToast?.('Erro ao remover anexo','error');}},
 updateExecutive(){const set=(id,v)=>{const e=document.getElementById(id);if(e)e.textContent=v};const printers=this.q('SELECT COUNT(*) FROM printers')[0]?.[0]||0;const printing=this.q("SELECT COUNT(*) FROM orders WHERE deleted_at IS NULL AND status='printing'")[0]?.[0]||0;const hours=this.q("SELECT SUM(COALESCE(print_time,0)) FROM orders WHERE deleted_at IS NULL AND status IN ('approved','paid','printing')")[0]?.[0]||0;const recv=this.q("SELECT SUM(MAX(COALESCE(total_price,0)-COALESCE(paid_amount,0),0)) FROM orders WHERE deleted_at IS NULL AND status NOT IN ('cancelled','quote')")[0]?.[0]||0;set('execPrinters',printers);set('execPrinting',printing);set('execQueueHours',Number(hours).toFixed(1)+' h');set('execReceivable',money(recv));},
 enhanceBootstrap(){
  document.querySelectorAll('.page-header').forEach(x=>x.classList.add('s5-page-header'));
  document.querySelectorAll('.toolbar-card').forEach(x=>x.classList.add('card','border-0','shadow-sm'));
  document.querySelectorAll('table').forEach(t=>{t.classList.add('table','table-hover','align-middle');if(!t.closest('.table-responsive')){const w=document.createElement('div');w.className='table-responsive';t.parentNode.insertBefore(w,t);w.appendChild(t)}})
 }
};
window.Sprint5=S5; window.openAttachments=(...a)=>S5.openAttachments(...a);
document.addEventListener('DOMContentLoaded',()=>{document.getElementById('notificationBell')?.addEventListener('click',()=>S5.showNotifications())});
window.addEventListener('load',()=>setTimeout(()=>{S5.enhanceBootstrap();S5.syncNotifications();S5.updateExecutive();setInterval(()=>{S5.syncNotifications();S5.updateExecutive()},60000)},1200));
})();
