let s6InstallPrompt=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();s6InstallPrompt=e;document.getElementById('pwaInstallBtn')?.classList.remove('d-none')});
window.addEventListener('appinstalled',()=>{s6InstallPrompt=null;document.getElementById('pwaInstallBtn')?.classList.add('d-none');showToast?.('Aplicativo instalado com sucesso','success')});
async function installSistema3D(){if(!s6InstallPrompt){showToast?.('A instalação já está ativa ou o navegador não oferece o botão.','info');return}await s6InstallPrompt.prompt();await s6InstallPrompt.userChoice;s6InstallPrompt=null}
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('/service-worker.js').catch(e=>console.warn('PWA',e)));
async function loadSprint6BackupConfig(){try{const c=await fetch('/api/backup/config').then(r=>r.json());document.getElementById('s6BackupEnabled').value=String(c.enabled!==false);document.getElementById('s6BackupFrequency').value=c.frequency||'daily';document.getElementById('s6BackupKeep').value=c.keep||30;const el=document.getElementById('s6BackupStatus');if(el)el.textContent=c.last_backup?'Último: '+new Date(c.last_backup).toLocaleString('pt-BR'):'Sem backup automático'}catch(e){console.warn(e)}}
async function saveSprint6BackupConfig(){const payload={enabled:document.getElementById('s6BackupEnabled').value==='true',frequency:document.getElementById('s6BackupFrequency').value,keep:+document.getElementById('s6BackupKeep').value};const r=await fetch('/api/backup/config',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(r=>r.json());showToast?.(r.ok?'Backup automático configurado':r.error,r.ok?'success':'error');loadSprint6BackupConfig()}
async function runSprint6Backup(){const r=await fetch('/api/backup/run',{method:'POST'}).then(r=>r.json());showToast?.(r.ok?'Backup criado: '+r.file:r.error,r.ok?'success':'error');loadSprint6BackupConfig()}
async function loadSprint6Backups(){try{const r=await fetch('/api/backup/list').then(r=>r.json());const el=document.getElementById('s6BackupList');if(el)el.innerHTML=(r.backups||[]).slice(0,10).map(b=>`<div class="d-flex justify-content-between border-bottom py-2"><span>${escapeHtml(b.name)}</span><span>${(b.size/1024).toFixed(1)} KB</span></div>`).join('')||'Nenhum backup encontrado.';}catch(e){const el=document.getElementById('s6BackupList');if(el)el.textContent='Não foi possível carregar a lista de backups.';console.warn('[Backup]',e);}}
function loadSprint6Users(){if(!window.db)return;const roles=db.exec('SELECT id,name FROM roles ORDER BY name')?.[0]?.values||[];const sel=document.getElementById('s6UserRole');if(sel)sel.innerHTML=roles.map(r=>`<option value="${r[0]}">${escapeHtml(r[1])}</option>`).join('');const users=db.exec(`SELECT u.id,u.name,u.email,COALESCE(r.name,'Sem perfil'),u.active FROM users u LEFT JOIN roles r ON r.id=u.role_id ORDER BY u.name`)?.[0]?.values||[];const list=document.getElementById('s6UsersList');if(list)list.innerHTML=users.map(u=>`<div class="list-group-item d-flex justify-content-between align-items-center"><div><strong>${escapeHtml(u[1])}</strong><div class="small text-secondary">${escapeHtml(u[2])} · ${escapeHtml(u[3])}</div></div><button class="btn btn-sm ${u[4]?'btn-outline-danger':'btn-outline-success'}" onclick="toggleSprint6User(${u[0]},${u[4]?0:1})">${u[4]?'Desativar':'Ativar'}</button></div>`).join('')||'<div class="text-secondary py-3">Nenhum usuário cadastrado.</div>'}
function saveSprint6User(){const name=document.getElementById('s6UserName').value.trim(),email=document.getElementById('s6UserEmail').value.trim().toLowerCase(),role=+document.getElementById('s6UserRole').value;if(!name||!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)){showToast?.('Informe nome e e-mail válido','error');return}try{db.run('INSERT INTO users(name,email,role_id,active,created_at) VALUES (?,?,?,?,?)',[name,email,role,1,new Date().toISOString()]);persistDB?.();loadSprint6Users();if(typeof loadSprint7UserOptions==='function')loadSprint7UserOptions();showToast?.('Usuário adicionado','success')}catch(e){showToast?.('E-mail já cadastrado','error')}}
function toggleSprint6User(id,active){db.run('UPDATE users SET active=? WHERE id=?',[active,id]);persistDB?.();loadSprint6Users()}
window.addEventListener('DOMContentLoaded',()=>setTimeout(()=>{loadSprint6BackupConfig();},700));
